### ISSUE TITLE
How to start...

### ISSUE THREAD

**Issue by Bacon-Ranch** [TomerFi/home_assistant_smartthings_bridge#1]
Hi, I'd love to give this a go, can you please provide basic instructions for a new user of hassio and raspberry pi 3 b+, very new user. I actually only use smartthings for a custom app called sportsnotifcations and 3 lights but would like to integrate it.

**Comment by TomerFi** [comment]
I'm sorry I haven't been checking, updating or using this repository for a long time.
I just came in now to mark it as "Not Maintained" and I saw your issue.

Please use HA's built in [smartthings components](https://www.home-assistant.io/components/#search/smartthings) instead.

Thank you,
And feel free to continue this discussion if there's anything I can help with,
even though it's marked as closed.
